---
  - name: "Creating dvd symbolic links"
    file:
      path: /var/www/html/os
      state: directory
      mode: 0755

  - name: "Creating symbolic links"
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      state: link
    with_items:
     - { src: '/mnt/rhel' , dest: '/var/www/html/os/rhel' }
     - { src: '/mnt/centos' , dest: '/var/www/html/os/centos' }
     - { src: '/mnt/ubuntu' , dest: '/var/www/html/os/ubuntu' }
